version: "3"

services:

    db:
        container_name: db
        image: "postgres" 
        env_file:
          - .env
        volumes:
          - postgres_data:/var/lib/postgresql/data 
        networks:
          - network-curumim-api

    api:
        container_name: api
        depends_on:
          - db
        build: .
        ports:
          - 3333:3333
        volumes:
          - .:/app
          - node_modules:/app/node_modules
        networks:
          - network-curumim-api
          
volumes: 
    postgres_data:
    node_modules:
      
networks:
  network-curumim-api: