version: "3"

services:
    api:
        container_name: api
        build: .
        ports:
          - 3333:3333
        volumes:
          - .:/app
          - node_modules:/app/node_modules
volumes: 
    postgres_data:
    node_modules:     